version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: task_db_container
    environment:
      POSTGRES_USER: niches
      POSTGRES_PASSWORD: "1969"
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U niches -d task_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: task_api_container
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_db
      SPRING_DATASOURCE_USERNAME: niches
      SPRING_DATASOURCE_PASSWORD: "1969"
      API_SECURITY_TOKEN_SECRET: YLBe37jPSS$$OQFjqu9zOTtivUK!haharWVD_QMXTRrZfnt$$gTHt#3HkFXL_81Qw6X2BxYjq866eq7m6#WPLCHUYvGWEqlxZg2x_XbhxxSU_3LwNjpobvQPJKP2#h3myinbXTWrcyv61eka3Jy!mMPPnuVvNVDNKqkaNiYSG!nuzQcpvlg3KZ8_O5q_273rORdNp8$$kOq
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_HBM2DDL_CREATE_NAMESPACES: "true"
volumes:
  postgres_data: